development:
  adapter: postgresql
  encoding: unicode
  database: lj_development
  pool: 5
  username: thinds
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: lj_test
  pool: 5
  username: thinds
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: lj_production
  pool: 5
  username: thinds
  password: 